### ISSUE TITLE
'pip: command not found'

### ISSUE THREAD

**Issue by elgehelge** [dbrgn/heroku-buildpack-python-sklearn#11]
Thanks for putting your work in developing the buildpack, just what I was looking for. Sadly I can't make it work. Anybody getting this error, or know how I might fix it?

remote: -----> Fetching set buildpack https://github.com/projetoeureka/heroku-buildpack-python-sklearn.git... done
remote: -----> Python app detected
remote: -----> No runtime.txt provided; assuming python-2.7.4.
remote: -----> Preparing Python runtime (python-2.7.4)
remote: -----> Installing Distribute (0.6.36)
remote: -----> Installing Pip (1.3.1)
remote: -----> Noticed numpy/scipy. Bootstrapping prebuilt binaries.
remote: -----> Creating/downloading binaries.
remote: Cloning into 'npscipy-binaries'...
remote: -----> Creating/downloading numpy bdist.
remote: -----> Creating/downloading scipy bdist.
remote: -----> Moving everything from venv directory to python directory...
remote: -----> Installing dependencies using Pip (1.3.1)
remote: -----> Noticed scikit-learn. Installing...
remote: -----> Setting environment vars...
remote: -----> Installing scikit-learn==0.13.1 via pip
remote: /tmp/buildpack20160216-168-vtxtxw/bin/steps/scikit-learn: line 34: pip: command not found
remote: 
remote:  !     Push rejected, failed to compile Python app

By looking at the comments on this blog post, it seems like other people are having a similar problem: https://blog.dbrgn.ch/2013/6/18/heroku-buildpack-numpy-scipy-scikit-learn/

**Comment by elgehelge** [comment]
Confused https://github.com/projetoeureka/heroku-buildpack-python-sklearn and https://github.com/dbrgn/heroku-buildpack-python-sklearn, so I did not se that the package is no longer maintained. I got it working using https://github.com/thenovices/heroku-buildpack-scipy

**Comment by dbrgn** [comment]
Great to hear that you got it working!
