### ISSUE TITLE
Any chance to get a more updated version of numpy and scipy?

### ISSUE THREAD

**Issue by AlJohri** [dbrgn/heroku-buildpack-python-sklearn#6]
Just curious if you would be able to precompile a more recent binary.

Thanks again for this!

**Newer Versions of scipy**
0.13.2
0.13.1
0.13.0
0.12.1
0.12.0
_0.11.0_ <--

**Newer Versions of numpy**
1.8.0
1.7.2
1.7.1
_1.7.0_ <--

**Newer Versions of scikit-learn**
0.14.1
0.14
_0.13.1_ <--

**Comment by AlJohri** [comment]
UPDATE: Found more recently compiled versions here: https://github.com/lell/npscipy-binaries

**Comment by dbrgn** [comment]
I'm currently in the hospital for a few days, I'll take a look at it when I'm back.

**Comment by ChristopherRabotin** [comment]
You can also use another buildpack such as https://github.com/thenovices/heroku-buildpack-scipy which is more up to date.

**Comment by dbrgn** [comment]
That could be a good idea, as I'm not using Heroku anymore, so I can't properly support this. @thenovices, are you planning on supporting your fork?

**Comment by branliu0** [comment]
More or less. I'll probably be using numpy/scipy on Heroku for a while, so it'll probably be supported. No guarantees though.

I'm using this buildpack on two projects I'm working on, so there are some other improvements to the buildpack that are coming too.

**Comment by ChristopherRabotin** [comment]
@thenovices , could you open up public issues on your repo then?

**Comment by branliu0** [comment]
Added.

**Comment by branliu0** [comment]
We can probably close this issue.

**Comment by dbrgn** [comment]
OK, in that case I'll update the README with disclaimers pointing to your fork. I'll close this issue as soon as this is done. Thanks for taking over! :)

**Comment by dbrgn** [comment]
Fixed by bd938080ddc2bb396bf0798496b5f8d14cdcfed7.
